package com.example_tastyfood_my_release_project_println_out_systems_food_tasty.presentation.screen.fragment.recyclerview.interfaces

import com.example_tastyfood_my_release_project_println_out_systems_food_tasty.domain.model.food.food_category.AllFoodCategoriesItem

interface ClickOnFoodCategory {

    fun clickOnFoodCategoryFromRcvAdapterFoodCategory(allFoodCategoriesItem: AllFoodCategoriesItem)

}